let Eletronica =[
    {
        id:1,
        img:'Medias/PlayListEletronica/Imagens/faded.jpg',
        NomeDaMusica:'Faded',
        Artista: 'Alam Walker',
        Audio:'Medias/PlayListEletronica/Audios/AlamWalkerFaded.mp3'
        
    },
    {
        id:2,
        img:'Medias/PlayListEletronica/Imagens/wakemeup.jpg',
        NomeDaMusica:'Wake Me Up',
        Artista: 'Avicii',
        Audio:'Medias/PlayListEletronica/Audios/Avicii-WakeMe-Up.mp3'

    },
    {
        id:3,
        img:'Medias/PlayListEletronica/Imagens/Summer.jpg',
        NomeDaMusica:'Summer',
        Artista: 'Calvin Harris',
        Audio:'Medias/PlayListEletronica/Audios/Calvin-Harris-Summer.mp3'

    },
    {
        id:4,
        img:'Medias/PlayListEletronica/Imagens/Titanium.jpg',
        NomeDaMusica:'Titanium',
        Artista: 'David Guetta',
        Audio:'Medias/PlayListEletronica/Audios/David-Guetta-Titanium.mp3'

    },
    {
        id:5,
        img:'Medias/PlayListEletronica/Imagens/Aromchupa.jpg',
        NomeDaMusica:'Im an Albatraoz',
        Artista: 'AronChupa e Little Sis Nora',
        Audio:'Medias/PlayListEletronica/Audios/AronChupa.mp3'

    },
    {
        id:6,
        img:'Medias/PlayListEletronica/Imagens/Showtek.jpg',
        NomeDaMusica:'Bad',
        Artista: 'David Guetta e Showtek',
        Audio:'Medias/PlayListEletronica/Audios/DavidGuetta-ShowtekBadftVassy.mp3'

    }
]
let Festival =[
    {
        id:1,
        img:'Medias/PlayListFestival/Imagens/Brimelliott.jpg',
        NomeDaMusica:'Terrified',
        Artista: 'Brynn Elliott',
        Audio:'Medias/PlayListFestival/Audios/BrynnElliottTerrified.mp3'
    },
    {
        id:2,
        img:'Medias/PlayListFestival/Imagens/uptownFunk.jpg',
        NomeDaMusica:'Uptown Funk',
        Artista: 'Mark Ronson ft. Bruno Mars',
        Audio:'Medias/PlayListFestival/Audios/UptownFunk.mp3'

    },
    {
        id:3,
        img:'Medias/PlayListFestival/Imagens/Beyonce_-_Halo.png',
        NomeDaMusica:'Halo',
        Artista: 'Beyoncé',
        Audio:'Medias/PlayListFestival/Audios/BeyoncéHalo.mp3'

    },
    
]
let Rock =[
    {
        id:1,
        img:'Medias/PlayListRock/Imagens/drsim.jpg',
        NomeDaMusica:'May the Force Be With You',
        Artista: 'Dr. Sin',
        Audio:'Medias/PlayListRock/Audio/DrSinMaytheforcebewithyou.mp3'
    },
    {
        id:2,
        img:'Medias/PlayListRock/Imagens/scorpions.jpg',
        NomeDaMusica:'Still Loving You',
        Artista: 'Scorpions',
        Audio:'Medias/PlayListRock/Audio/ScorpionsStillLovingYou.mp3'
    },
    {
        id:3,
        img:'Medias/PlayListRock/Imagens/whinofchange.jpg',
        NomeDaMusica:'Wind of Change',
        Artista: 'Scorpions',
        Audio:'Medias/PlayListRock/Audio/ScorpionsWindOfChange.mp3'
    },
    {
        id:4,
        img:'Medias/PlayListRock/Imagens/whinofchange.jpg',
        NomeDaMusica:'Send Me an Angel',
        Artista: 'Scorpions',
        Audio:'Medias/PlayListRock/Audio/ScorpionsSendMeAnAngel.mp3'
    },
    {
        id:5,
        img:'Medias/PlayListRock/Imagens/acoustica.jpg',
        NomeDaMusica:'Always Somewhere',
        Artista: 'Scorpions',
        Audio:'Medias/PlayListRock/Audio/ScorpionsAlwaysSomewhere.mp3'
    },
    {
        id:6,
        img:'Medias/PlayListRock/Imagens/direstraits.jpg',
        NomeDaMusica:'Sultans of Swing',
        Artista: 'Dire Straits',
        Audio:'Medias/PlayListRock/Audio/DireStraitsSultansOfSwing.mp3'
    },
    {
        id:7,
        img:'Medias/PlayListRock/Imagens/guns.jpg',
        NomeDaMusica:'Sweet Child O Mine',
        Artista: 'Guns N Roses',
        Audio:'Medias/PlayListRock/Audio/GunsNRosesSweetChildOMineOfficial.mp3'
    },
    {
        id:8,
        img:'Medias/PlayListRock/Imagens/Metallica.jpg',
        NomeDaMusica:'Nothing Else Matters',
        Artista: 'Metallica',
        Audio:'Medias/PlayListRock/Audio/MetallicaNothingElseMatters.mp3'
    },
    
]
let Acustica =[
    {
        id:1,
        img:'Medias/PlayListAcustica/Imagens/Jorgeversilo.jpg',
        NomeDaMusica:'Homem-Aranha',
        Artista: 'Jorge Vercillo',
        Audio:'Medias/PlayListAcustica/Audios/JorgeVercilloHomemAranha.mp3',
        letra :['Eu adoro andar no abismo',
        'Numa noite vil de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Eu adoro andar no abismo',
        'Numa noite viril de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Tenho um grande golpe pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas su,as mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia']
    },
    {
        id:2,
        img:'Medias/PlayListAcustica/Imagens/Jorgeversilo.jpg',
        NomeDaMusica:'Monalisa ',
        Artista: 'Jorge Vercillo',
        Audio:'Medias/PlayListAcustica/Audios/JorgeVercilloMonalisa.mp3',
        letra :['Eu adoro andar no abismo',
        'Numa noite vil de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Eu adoro andar no abismo',
        'Numa noite viril de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Tenho um grande golpe pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas su,as mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia']
    },
    {
        id:3,
        img:'Medias/PlayListAcustica/Imagens/Jorgeversilo.jpg',
        NomeDaMusica:'Que Nem Maré ',
        Artista: 'Jorge Vercillo',
        Audio:'Medias/PlayListAcustica/Audios/JorgeVercilloQueNemMaré.mp3',
        letra :['Eu adoro andar no abismo',
        'Numa noite vil de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Eu adoro andar no abismo',
        'Numa noite viril de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Tenho um grande golpe pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas su,as mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia']
    },
    {
        id:4,
        img:'Medias/PlayListAcustica/Imagens/Jorgeversilo.jpg',
        NomeDaMusica:'Final Feliz',
        Artista: 'Jorge Vercillo',
        Audio:'Medias/PlayListAcustica/Audios/JorgeVercilloFinalFeliz.mp3',
        letra :['Eu adoro andar no abismo',
        'Numa noite vil de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Eu adoro andar no abismo',
        'Numa noite viril de perseguição',
        'Saltando entre os edifícios',
        'Vi você',
        'Em poder de um fugitivo',
        'Que cercado pela polícia te fez refém lá nos precipícios',
        'Foi paixão à primeira vista',
        'Me joguei de onde o céu arranha',
        'Te salvando com a minha teia',
        'Prazer, me chamam de Homem-Aranha',
        'Seu herói',
        'Hoje o herói aguenta o peso das compras do mês',
        'No telhado, ajeitando a antena da tevê',
        'Acordado a noite inteira pra ninar bebê',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Chega de assalto pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas suas mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia',
        'Chega de bandido pra prender',
        'De bala perdida pra deter',
        'Eu tenho uma ideia',
        'Você na minha teia',
        'Tenho um grande golpe pra impedir',
        'Seja em Brasília ou aqui',
        'Eu tive a grande ideia',
        'Você na minha teia',
        'Hoje eu estou nas su,as mãos',
        'Nessa sua ingênua sedução',
        'Que me pegou na veia',
        'Eu to na tua teia']
    },
    
]
let Cover =[
    {
        id:1,
        img:'Medias/PlayListCover/Imagens/BiaMaques.jpg',
        NomeDaMusica:'Nosso quadro Ana Castela',
        Artista: 'Bia Marques cover',
        Audio:'Medias/PlayListCover/Audios/NossoquadroAnaCastelaBiaMarquescover.mp3'
    },
    {
        id:2,
        img:'Medias/PlayListCover/Imagens/amarina.jpg',
        NomeDaMusica:'Amarelo, azul e branco| Anavitória e Rita Lee',
        Artista: 'Amarina',
        Audio:'Medias/PlayListCover/Audios/AMARELOAZULEBRANCOAnavitóriaCoverdeAMARINA.mp3'
    },
    {
        id:3,
        img:'Medias/PlayListCover/Imagens/amarina.jpg',
        NomeDaMusica:'MASHUP FORRÓ',
        Artista: 'Amarina',
        Audio:'Medias/PlayListCover/Audios/MASHUPFORRÓCoverdeAMARINA.mp3'
    },
    {
        id:4,
        img:'Medias/PlayListCover/Imagens/amarina.jpg',
        NomeDaMusica:'ANUNCIAÇÃO | Alceu Valença',
        Artista: 'Amarina',
        Audio:'Medias/PlayListCover/Audios/ANUNCIAÇÃOAlceuValençaCoverdeAMARINA.mp3'
    },
    {
        id:5,
        img:'Medias/PlayListCover/Imagens/amarina.jpg',
        NomeDaMusica:'SAMURAI | Djavan',
        Artista: 'Amarina',
        Audio:'Medias/PlayListCover/Audios/SAMURAIDjavanCoverdeAMARINA.mp3'
    },
    {
        id:6,
        img:'Medias/PlayListCover/Imagens/BiaMaques.jpg',
        NomeDaMusica:'Cartão Black',
        Artista: 'Bia Marques cover',
        Audio:'Medias/PlayListCover/Audios/CartãoBlackBiaMarquescover.mp3'
    },
    {
        id:7,
        img:'Medias/PlayListCover/Imagens/BiaMaques.jpg',
        NomeDaMusica:'Se for amor | João Gomes',
        Artista: 'Bia Marques cover',
        Audio:'Medias/PlayListCover/Audios/seforamorbiamarques.mp3'
    },
    {
        id:8,
        img:'Medias/PlayListCover/Imagens/BiaMaques.jpg',
        NomeDaMusica:'Eu tenho medo | Zé Vaqueiro',
        Artista: 'Bia Marques cover',
        Audio:'Medias/PlayListCover/Audios/EutenhomedoZéVaqueiroBiaMarquescover.mp3'
    },
    {
        id:9,
        img:'Medias/PlayListCover/Imagens/amarinacover.jpg',
        NomeDaMusica:'MALANDRAGEM | Cássia Eller',
        Artista: 'Amarina',
        Audio:'Medias/PlayListCover/Audios/malandragemAmarina.mp3'
    },
    {
        id:10,
        img:'Medias/PlayListCover/Imagens/hqBia.jpg',
        NomeDaMusica:'Surreal ',
        Artista: 'Bia Marques cover',
        Audio:'Medias/PlayListCover/Audios/SurrealversãoBiaMarques.mp3'
    },
    
    {
        id:11,
        img:'Medias/PlayListCover/Imagens/amarinacover.jpg',
        NomeDaMusica:'MONALISA | Jorge Vercillo',
        Artista: 'Amarina',
        Audio:'Medias/PlayListCover/Audios/MONALISAJorgeVercilloCoverdeAMARINA.mp3'
    },
]
JSON.stringify(Eletronica)
JSON.stringify(Festival)
JSON.stringify(Rock)
JSON.stringify(Acustica)
JSON.stringify(Cover)